### ISSUE TITLE
pi값이 제멋대로 바뀝니다.

### ISSUE THREAD

**Issue by papercore-dev** [sw08/pi#1]
**1차시도** - 3.1415876535897618
**2차시도** - 3.141590153589744
**3차시도** - 3.1415909869230147
**4차시도** - 3.1415914035897172
---
아무래도 Math.JS 프레임워크 쓰셔야 정확한 연산이 될거같네요.
JS의 소수점 연산은 못 믿어요.

**Comment by sw08** [comment]
(사실 이거 예전에 js 배우려고 할때 응용처럼 만들어본 거였어요)
나중에 js 배우면 고칠게요
+ 제가 쓰는 방식은 버튼 누를때마다 더 계산을 하는 방식이에요
